[package]
name = "update_system_c"
version = "0.1.0"
authors = ["Vincent RouilleÌ <vincent@speedy37.fr>"]

[dependencies]
env_logger = "0.6"
updater = { path = "../../updater" }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
