[package]
name = "update_system_c"
version = "0.1.0"
authors = ["Vincent RouilleÌ <v-rouille@logitud.fr>"]

[dependencies]
update_system = { path = "../../" }
clap = "2.29.0"

[lib]
crate-type = ["cdylib"]
